### ISSUE TITLE
Swagger & Express

### ISSUE THREAD

**Issue by danielneri** [feathersjs-ecosystem/feathers-swagger#106]
Thanks for the library. I'm having some trouble getting this working when using Express as my transport provider:

### Steps to reproduce

Requires feathers, express, and feathers-swagger.

- [x] Tell us what broke. The more detailed the better.
- [x] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

https://gist.github.com/danielneri/bee112e16ef907a47c758756b112c58e

### Expected behavior

Docs should generate.

### Actual behavior

/docs renders a 404 error.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

feathers-swagger-test@1.0.0 /Users/...
├── body-parser@1.18.3
├── feathers@2.2.4
├── feathers-memory@2.1.1
├── feathers-rest@1.8.1
└── feathers-swagger@0.6.0

**NodeJS version**:

v8.11.2

**Operating System**:

macOS High Sierra

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by danielneri-accesso** [comment]
Turns out this was user error, I had placed this in the wrong file :(

I can confirm this library works great, even with Express as the transport layer.

**Comment by danielneri** [comment]
Turns out this was user error, I had placed this in the wrong file :(

I can confirm this library works great, even with Express as the transport layer.
