### ISSUE TITLE
Code generated using feathers cli, unable to use swagger with authentication

### ISSUE THREAD

**Issue by HarisHashim** [feathersjs-ecosystem/feathers-swagger#107]
## ## Steps to reproduce

- [x] Tell us what broke. The more detailed the better.

I have tried to troubleshoot this as per issue  #36 . But so far never got it working.

I have feathers-swagger working up to displaying Swagger UI and using it to execute get and post for services that does not require authentication.

However after enabling authentication, I got error as per bellow screenshot:

![error](https://user-images.githubusercontent.com/1856131/40616103-3e69ae28-62bc-11e8-9182-054f35c73fc1.png)
The reply at the end of Issue #35 might have similar problem.

Bellow code is in messages.services.js
```
const messages = createService(options);
  messages.docs = {
    description: "A service to send and receive chat messages",
    definitions: {
      messages: {
        type: "object",
        required: ["text"],
        properties: {
          text: {
            type: "string",
            description: "The message text"
          },
          userId: {
            type: "string",
            description: "The id of the user that send the message"
          }
        }
      }
    }
  };

  app.use("/messages", messages);
```

And this one in app.js
```
//Swagger
app.configure(
  swagger({
    docsPath: "/docs",
    uiIndex: true,
    info: {
      title: "Feathers Chat Backend",
      description: "Feathers chat backend!"
    },
   securityDefinitions: {
      bearer: {
        type: "apiKey",
        name: "authorization",
        in: "header"
      }
    },
    security: [
      {
        bearer: []
      }
    ]
  })
);
```

- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

I have created example to demonstrate this issue using feathers-chat repo

[Github - feathers-chat-swagger](https://github.com/HarisHashim/feathers-chat-swagger)

### Expected behavior

As per #36 I did see bellow screen. So something work. But expected get and post for authenticated service to work.

![image](https://user-images.githubusercontent.com/1856131/40616441-a1b641d4-62bd-11e8-9604-cf8a3843db36.png)

**Comment by HarisHashim** [comment]
@daffl & @ideally , appreciate your help. 

I have tried 

```
securityDefinitions: {
      bearer: {
        type: "apiKey",
        name: "authorization",
        in: "header"
      }
    },
    security: [
      {
        bearer: []
      }
    ]
```

and 

```

    security: {
      name: "jwt",
      type: "apiKey",
      in: "header"
    },
    securityDefinitions: {
      jwt: {
        type: "apiKey",
        name: "Authorization",
        in: "header"
      }
    }
```

Does it have something to do with authentication method using local authentication strategy? Or wrong securityDefinitions? Or something change in latest swagger library that I have to specify swagger 2.0?

**Comment by HarisHashim** [comment]
Wow! Can't imagine I wrote all those. Must be a bad case of alien possession.

Or perhaps it is time to retrace the step and remember what the hell this is about!

**Comment by Mairu** [comment]
Authentication has to be configured and should work when done correctly with version 1.0.0. See also the examples folder for help.
