### ISSUE TITLE
Log statement in the code: Remove it?

### ISSUE THREAD

**Issue by andys8** [feathersjs-ecosystem/feathers-swagger#110]
There is a `log` statement inside the code. Should this be the case and users not being able to deactivate it?

https://github.com/feathersjs-ecosystem/feathers-swagger/blob/8f4a3a4ad94de8d7e5db7637d85a94b4a3ac28de/lib/index.js#L69

```shell
console.log node_modules/feathers-swagger/lib/index.js:69
      Adding static path /<path>/node_modules/swagger-ui-dist
```

**Comment by daffl** [comment]
Yep, it should definitely be removed. `debug` statements would be nice though.

**Comment by andys8** [comment]
Removed it, because even for a `console.debug` the user can not decide against it otherwise.

**Comment by daffl** [comment]
Sorry, I meant adding debugging statements using the [Node debug](https://www.npmjs.com/package/debug) module. Thanks for the PR though, that definitely shouldn't be in there.
