### ISSUE TITLE
How to add POST /authentication to create the JWT?

### ISSUE THREAD

**Issue by alinex** [feathersjs-ecosystem/feathers-swagger#136]
### Steps to reproduce

I use JWT authentication through the /authentication path, but I am missing a possibility to easily create the JWT through Swagger. It is only possible to authenticate in swagger with an already retrieved JWT.

### Expected behavior

I would like to have an /authorization POST call to be used like all the other services.
Or directly allow to generate the token within the authorization dialog of swagger.

### Actual behavior

Only normal services are shown with their methods, not the authentication service.

### System configuration

My config looks like:

      security: [
        {
          APIKeyHeader: []
        }
      ],
      securityDefinitions: {
        APIKeyHeader: {
          type: "apiKey",
          name: "Authorization",
          in: "header"
        }
      }

I am using:

    ├─┬ feathers-swagger@0.7.2
    │ ├─┬ swagger-ui@3.21.0
    │ │ ├─┬ swagger-client@3.8.25
    │ └── swagger-ui-dist@3.21.0

**Comment by Mairu** [comment]
This is not directly related to feathers-swagger. But as I was also interested in this feature I wrote a [plugin](https://github.com/Mairu/swagger-ui-apikey-auth-form) for Swagger UI to add the possiblity to create the bearer (jwt) token using a callback. In this callback you can call the authenticate endpoint.

I added it to the security example for openapi v 3, but this should also work for swagger v2.
