### ISSUE TITLE
Updating to 1.0.0 from 0.7.3 breaks docs page

### ISSUE THREAD

**Issue by EspadaV8** [feathersjs-ecosystem/feathers-swagger#146]
### Steps to reproduce

I've attempted to update a project that is using 0.7.3 to 1.0.0 and using the 2.0 generator breaks the docs page.

### Expected behaviour

Docs page should render

### Actual behaviour

ReDoc (the UI we're using) complains that `leave` definition isn't defined (a model we use). Looking at the generated docs it looks like anything defined in our `app.model.js` file isn't used in the final output so any 'global' definitions we have are missing.

I will attempt to create a small repo to reproduce the issue or see if I can find out what's happening.

**Comment by Mairu** [comment]
Well there were several breaking changes, so configuration and definition of docs has to be adjusted.

**Comment by Mairu** [comment]
@EspadaV8 Any news?

**Comment by Mairu** [comment]
Closing as there was no further information. Feel free to reopen with additional information.
