### ISSUE TITLE
Feature: Add support for multiple host in OpenAPI v3

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs-ecosystem/feathers-swagger#153]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to add `Servers` option into `swagger-config` for `openApiVersion` 3.

```
app.configure(swagger({
  // Unable to configure for Servers {url}
  openApiVersion: 3,
  idType: 'string',
  docsPath: '/docs',
  uiIndex: path.join(__dirname, 'docs.html'),
  specs: {
    info: {
      title: 'API',
      description: 'API',
      version: '1.0.0',
    },
  },
}));
```

**Describe the solution you'd like**
Provide the option to allow to input `Servers` url as seen in [swagger.io](https://swagger.io/docs/specification/basic-structure/)

**Additional Info**
Adding multiple hosts is added only to `OpenAPI` v3. See [api-host-and-base-path](https://swagger.io/docs/specification/api-host-and-base-path/)

**Update**
Not sure if I missed out, but it seem like there is no option to add `hosts` and `basepath` in `v2`. See [api-host-and-base-path-v2](https://swagger.io/docs/specification/2-0/api-host-and-base-path/)

**Comment by Mairu** [comment]
The specs option is there to add any specifications into the generated document.

```
app.configure(swagger({
  // Unable to configure for Servers {url}
  openApiVersion: 3,
  idType: 'string',
  docsPath: '/docs',
  uiIndex: path.join(__dirname, 'docs.html'),
  specs: {
    info: {
      title: 'API',
      description: 'API',
      version: '1.0.0',
    },
    servers: [
      {
        url: 'https://api.example.com/v1',
        description: 'Production server (uses live data)',
      },
      {
        url: 'https://sandbox-api.example.com:8443/v1',
        description: 'Sandbox server (uses test data)',
      },
    ],
  },
}));
```

**Comment by bwgjoseph** [comment]
Sorry, my bad. And thank you.
