### ISSUE TITLE
Define model in json file

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs-ecosystem/feathers-swagger#155]
Hi,

I am trying out `schemasGenerator` and it works just fine if I define everything without a standalone json file as below.

**video.server.ts**
```
// An extract
const cService = createService(options);

  cService.model = {
    type: 'object',
    required: [
      'id',
    ],
    properties: {
      id: { type: 'number' },
      b: { type: 'string' },
      start_date: {
        $ref: '#/components/schemas/ISODateFormat'
      },
      c: { type: 'number' },
      d: { type: 'number' },
      e: { type: 'string' }
    },
  };

  cService.docs = {
    description: 'Service to manage video',
    multi: ['create'],
  };
```

**app.ts**
```
app.configure(swagger({
  openApiVersion: 3,
  idType: 'string',
  docsPath: '/docs',
  docsJsonPath: "/jsondocs",
  uiIndex: true,
  specs: {
    info: {
      title: 'API',
      description: 'API',
      version: '1.0.0',
    },
    servers: [{
      url: 'http://localhost:3030',
      description: 'Production server (uses live data)'
    },
    {
      url: 'http://sandbox-api.example.com:8443/v1',
      description: 'Sandbox server (uses test data)'
    }
    ],
    components: {
      schemas: {
        ISODateFormat: {
          description: 'ISO format date-time.',
          example: '2018-01-01T01:01:01.001Z',
          format: 'date-time',
          readOnly: true,
          type: 'string'
        },
      }
    }
  },
  defaults: {
    schemasGenerator(service, model, modelName) {
      return {
        [model]: service.model,
        [`${model}_list`]: {
          title: `${modelName} list`,
          type: 'array',
          items: { $ref: `#/components/schemas/${model}` }
        },
      };
    }
  }
}));
```

In the `GET` path portion of the UI

![image](https://user-images.githubusercontent.com/37484538/60037711-e1695f80-96e4-11e9-8725-ff574ff4040c.png)

However, if I extract the definition of `cService.model` into a `.json` file by itself as such..

**video.json**
```
{
  "type": "object",
  "required": [
    "id"
  ],
  "properties": {
    "id": {
      "type": "number"
    },
    "b": {
      "type": "string"
    },
    "start_date": {
      "$ref": "#/components/schemas/ISODateFormat"
    },
    "c": {
      "type": "number"
    },
    "d": {
      "type": "number"
    },
    "e": {
      "type": "string"
    }
  }
}
```

Update `video.service.ts` to
```
import * as video_model from video.json

  const cService = createService(options);
  
  cService.model = video_model;

  cService.docs = {
    description: 'Service to manage video',
    multi: ['create'],
  };
```

The result will become like this.

![image](https://user-images.githubusercontent.com/37484538/60037785-27bebe80-96e5-11e9-9e72-36fda593841b.png)

Is it because I can't import and define a standalone json? Or did I do it wrongly?

Any idea what is causing this?

Thanks!

**Comment by Mairu** [comment]
Import the JSON from an external file should lead to exactly the same behavior.
Importing JSON in TypeScript has to be done without `as *` if you want only the JSON content to be imported. I guess that this is your problem.

**Comment by bwgjoseph** [comment]
Hi @Mairu,

Thank you once again for help. Am currently using `typescript v3.5.2`, and there is no need to define `resolveJsonModule: true` in `tsconfig.json`.

I just have to import using `import video_model from video.json` without `* as` and it works just fine.

---

Do you have any idea why `start_date` is not showing in the filter option?

![image](https://user-images.githubusercontent.com/37484538/60037711-e1695f80-96e4-11e9-8725-ff574ff4040c.png)

---

And lastly, another related question. As you can see that I am currently defining model in `video.service.ts` as such.

```
import video_model from './video.json'

cService.model = video_model;
```

The definition for the model, and the JSON schema definition in `video.schema.ts` generated by `feathers-plus-cli` is almost similar yet with a small differences in certain definition.

```
// Define the model using JSON-schema
let schema = {
  // !<DEFAULT> code: schema_header
  title: 'Video',
  description: 'Video database.',
  // !end
  // !code: schema_definitions // !end

  // Required fields.
  required: [
    'id',
    // !code: schema_required // !end
  ],
  // Fields with unique values.
  uniqueItemProperties: [
    // !code: schema_unique // !end
  ],

  // Fields in the model.
 properties: {
    // !code: schema_properties
    id: { type: 'number' },
    b: { type: 'string' },
    start_date: { $ref: 'common.json#/definitions/ISODateFormat' },
    c: { type: 'number' },
    d: { type: 'number' },
    e: { type: 'string' }
    // !end
  },
  // !code: schema_more // !end
};
```

So I'm trying to re-use the schema defined in `video.schema.ts` instead of having to re-define another `video.json` which makes it difficult to maintain. So this is what I did.

```
import v from './video.schema';

cService.model = v.schema;
```

Works great except that it is not able to `ref` to `ISODateFormat`. My guess is due to `openApi v3`, the `definition` changed to `component/schema`.

![image](https://user-images.githubusercontent.com/37484538/60198037-481c8380-9873-11e9-9981-8abc5b6a6b0b.png)

*Note that `ISODateFormat` is `ref` to `common.json` for the definition.

Is there any way to achieve this? Re-using `video.schema.ts` instead of having to define another `video.json` for the `cService.model`.

Thanks!

**Comment by Mairu** [comment]
You can also use external refs in swagger. If you have a ref that refers to an external file, this file has to be reachable under the same path used for docsJsonPath (or docsPath if docsJsonPath is not used). The "internal" path in the external path can be definitions or anything else.

So the important thing is, that if you use /jsondocs as the docsJsonPath, that /common.json is pointing to your common.json. If you you use /docs/app.json it would be /docs/common.json.

**Comment by bwgjoseph** [comment]
Hi,

Sorry, but I don't quite get what you meant but...

This is my current directory structure.

![image](https://user-images.githubusercontent.com/37484538/60274593-e7e91880-992a-11e9-9009-ccb2f787ccb2.png)

So in `app.ts`, I have the following:

```
app.configure(swagger({
  openApiVersion: 3,
  idType: 'string',
  docsPath: '/docs',
  docsJsonPath: "/jsondocs",
....
```

The only way that I got it working is by copying `common.json` to `/public` directory so that it can be served and accessed. Otherwise, if it is inside `src/refs/common.json`, it is not able to resolve, and will prompt error when I access `swagger-ui` docs.

Is that the right way?

And even though there is no error, I noticed by that doing so, the `filter` portion seem to not have the object as seen (in the previous post). But I am still able to perform the `get` query. Not sure if I did any steps wrong here.

![image](https://user-images.githubusercontent.com/37484538/60278255-adcf4500-9931-11e9-832c-cc65b313f40d.png)

**Comment by Mairu** [comment]
You can serve the common.json with a custom path by using express directly.

In app.ts use 
```javascript
  app.route('/common.json').get((req, res) => {
    res.sendFile(path.join(__dirname, 'refs', 'common.json')); // could be different if you compile ts to js into another directory without copying the json files
  });
```

That the referenced parameter is not shown for filter parameters is because of the readOnly flag of the ISODateFormat.

**Comment by bwgjoseph** [comment]
Hi,

After playing around with it, I learnt something new. 
For the benefit of those that come after.

All the fields in `filter` parameter wasn't showing wasn't due to `readOnly` flag in `ISODateFormat`. It wasn't showing because I did not set the `type: 'object` in `video.schema.ts`.

I added the custom route to serve `common.json`.

Updated `video.schema.ts` 

```
let schema = {
  // !<DEFAULT> code: schema_header
  title: 'Video',
  description: 'Video database.',
  // !end
  // !code: schema_definitions // !end
  // Need to set this to show in filter parameter
  type: 'object',
  // Required fields.
  required: [
    // !code: schema_required // !end
  ],
  // Fields with unique values.
  uniqueItemProperties: [
    // !code: schema_unique // !end
  ],

  // Fields in the model.
  properties: {
    // !code: schema_properties
    id: { type: 'number' },
    b: { type: 'string' },
    start_date: { $ref: 'common.json#/definitions/ISODateFormat' },
    c: { type: 'number' },
    d: { type: 'number' },
    e: { type: 'string' }
    // !end
  },
  // !code: schema_more // !end
};
```

Toggling `readOnly` flag of a field will only show/hide in the `filter` parameter.

`readOnly: false`

![image](https://user-images.githubusercontent.com/37484538/60288903-c5b1c380-9947-11e9-93a1-699ab6503a5f.png)

`readOnly: true`. `start_date` will no longer be shown.

![image](https://user-images.githubusercontent.com/37484538/60288942-d9f5c080-9947-11e9-873b-b3d57230bca4.png)

Thank you once again, @Mairu, for assisting me.
