### ISSUE TITLE
Support for non-feathers middleware service documentation

### ISSUE THREAD

**Issue by RickEyre** [feathersjs-ecosystem/feathers-swagger#156]
I've created a custom middleware service in my feathers app for document uploading / downloading. 

This library works beautifully for documenting my feathers services, but I'm struggling to find how I can add in my custom swagger docs for this one off middleware I made.

**Comment by Mairu** [comment]
When I understand you correctly, you added additional routes with a custom middleware and want to document them using swagger.

When this is the case, you could add them to the generated specifications. They are available as app.docs after calling swagger (from feathers-swagger). There is also the option **appProperty** to use a different name for this.

There you could add your routes into the paths property. Automatic generation is not possible in this case.
