### ISSUE TITLE
Defining authentication endpoint

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs-ecosystem/feathers-swagger#157]
Hi,

I generated `authentication` endpoint, and the swagger docs automatically added the service into it. And I am unable (or rather not sure) how to override the config to show the `authentication` object and endpoint correctly.

With the default, after generating the `authentication` service.

![image](https://user-images.githubusercontent.com/37484538/60398246-c2f1e100-9b88-11e9-872f-80dee2cd5265.png)

![image](https://user-images.githubusercontent.com/37484538/60398248-cb4a1c00-9b88-11e9-92c2-725158b703da.png)

Expanding the `/post authentication`

![image](https://user-images.githubusercontent.com/37484538/60398253-e321a000-9b88-11e9-91a4-872b2be3af74.png)

---

One way I did initially was to exclude it

```
ignore: {
    tags: ['authentication'],
```

but doesn't seem right. I would probably need that endpoint there. So I can't exclude it.

---

After generating the `authentication` service, `authentication.ts` file is generated.

This is what is generated. Then I added `.docs` portion but swagger doesn't seem to pick up.

```
let moduleExports = function (app: App) {
  const config = app.get('authentication');
  // !code: func_init // !end

  // Set up authentication with the secret
  app.configure(authentication(config));
  app.configure(jwt());
  app.configure(local());
  // !code: loc_1 // !end

  // !code: loc_2 // !end
  // I tried to add this in here but doesn't work
  (app as any).service('authentication').docs = {
    components: {
      schemas: {
        authentication: {
          type: 'object',
          properties: {
            strategy: { type: 'string' },
            email: { type: 'string' },
            password: { type: 'string' }
          }
        }
      }
    }
  };

  // The `authentication` service is used to create a JWT.
  // The before `create` hook registers strategies that can be used
  // to create a new valid JWT (e.g. local or oauth2)
  (app as any).service('authentication').hooks({
    before: {
      create: [
        // !<DEFAULT> code: before_create
        authentication.hooks.authenticate(config.strategies),
        // !end
      ],
      remove: [
        // !<DEFAULT> code: before_remove
        authentication.hooks.authenticate('jwt'),
        // !end
      ],
      // !code: before // !end
    },
    // !code: after // !end
  });
  // !code: func_return // !end
};

// !code: exports // !end
export default moduleExports;
```

Then I tried to add in `app.ts`

```
app.configure(swagger({
  openApiVersion: 3,
  idType: 'string',
  docsPath: '/docs',
  docsJsonPath: '/jsondocs',
  uiIndex: true,
  specs: {
    info: {
      title: 'API',
      description: 'API',
      version: '1.0.0',
    },
    servers: [{
      url: 'http://localhost:3030',
      description: 'Production server (uses live data)'
    },
    {
      url: 'http://sandbox-api.example.com:8443/v1',
      description: 'Sandbox server (uses test data)'
    }
    ],
  // doesn't pick up as well
    components: {
      schemas: {
        authentication: {
          type: 'object',
          properties: {
            strategy: { type: 'string' },
            email: { type: 'string' },
            password: { type: 'string' }
          }
        }
      }
    }
  },
```

and the `defaults schemasGenerator` is generating `authentication list` (as shown in the image above) under `schemas` which should not happen since there is no `/GET` request, so it doesn't make any sense to do so.

Hence I tried to check for `service.model` name and tried to return but not too sure how to get it working too.

```
defaults: {
    schemasGenerator(service, model, modelName) {
      // can't do this
      // if (modelName === 'authentication') return;
      return {
        [model]: service.model,
        [`${model}_list`]: {
          title: `${modelName} list`,
          type: 'array',
          items: { $ref: `#/components/schemas/${model}` }
        },
      };
    }
  }
```

So I guess my questions is..

1. How do or where do I define the `.docs` for `authentication` to define my `schema definition` in order for `swagger` to read and display correctly.
2. How to prevent `schemasGenerator` from generating `[${model}_list]` for `authentication` endpoint, and only the `[model]`.
3. I have applied global `BearerAuth` security but would like to disable for `/POST authentication` endpoint.

Thank you.

**Comment by Mairu** [comment]
To answer your questions:

1. This is not possible at the moment. The reason is that the docs option of a service has to be defined before it is registered. The service for authentication is registered internally and you don't have a way to customize it (in version 3 of feathers).

So I would propose to register feathers-swagger after the authentication so that this service will not be "documented".
If you want you could then document it manually, by providing the paths objects to the specs options when initializing feathers-swagger.

2. This should work.

3. How did you define that in a global way? (For swagger specification: if you set an empty array for the security property of a path/operation it should not have an authentication method)

**Comment by bwgjoseph** [comment]
Hi,

1. I tried to register `feathers-swagger` after registering `authentication` as you mentioned, and it did work. And then I setup the `path` myself, and it worked as well. 
Then I went back to let the `feathers-swagger` register before `authentication`, just to see if I could make it work the same as well.

2. Previously, I did not return a empty object hence, I could not skip the `authentication` schema from generating the default. 
To fix it, simply do `if (modelName === 'authentication') return {};`.

3. I defined this under the `specs`

```
components: {
      securitySchemes: {
        BearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT'
        }
      },
```
Somehow, when I tried it earlier on, when I did a `POST` on `/authentication` path, it is asking me for `accessToken`. I tried it again, and now it is working as it should be. I'm guessing I did something wrong previously.

---

Now with those solved, I would like to know how I can override certain properties that is generated by `schemasGenerator`. For example, setting the security, or response of a specific request.

1. Override the security portion. I guess this is not possible as you previously mentioned but just like to confirm once more. As I had register `swagger` before `authentication`, I am unable to make any more changes right?

So specifying this under `spec` wouldn't do a thing?

```
paths: {
      '/authentication/{_id}': {
        post: {
          security: [{
            BearerAuth: []
          }],
        }
      }
    },
```

2. Overriding a specific response, say `GET /user` endpoint.

In `user.service.ts`, I added the following..

```
cService.docs = {
    description: 'Service to manage user',
    // Can use all or define individual method type
    securities: ['all'],
    components: {
      schemas: {
        userResponse: {
          type: 'object',
          properties: {
            a: { type: 'number' },
            b: { type: 'string' },
            start_date: { $ref: 'common.json#/definitions/ISODateFormat' },
          }
        }
      }
    },
    operations: {
      find: {
        'responses.200': {
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/userResponse'
              }
            }
          }
        }
      }
    }
  };
```

I am able to override the `find.responses.200` but it is not able to locate `userResponse`.

![image](https://user-images.githubusercontent.com/37484538/60454756-44b83c00-9c67-11e9-8c48-fb2a532a7ca6.png)

If I placed `userResponse` in `app.ts` when configuring `swagger options`, it would be able to locate. How should I define it in `user.service.ts` so that it can locate `userResponse` as well? 

Thanks!

**Comment by Mairu** [comment]
1. When you define the object for paths yourself and provide it when initializing feathers-swagger, you can provide all properties that openapi supports, so it should be able to define the security for a path. But it has to be a complete object, not just security.

2. To define schemas in the service.docs just use schemas (or definitions) without components.

**Comment by bwgjoseph** [comment]
Did you mean that I have to provide the entire `path` definition for the particular endpoint?

```
"paths": {
    "/authentication": {
      "post": {
        "parameters": [],
        "responses": {
          "201": {
            "description": "created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/authentication"
                }
              }
            }
          },
          "401": {
            "description": "not authenticated"
          },
          "500": {
            "description": "general error"
          }
        },
        "description": "Creates a new resource with data.",
        "summary": "",
        "tags": ["authentication"],
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/authentication"
              }
            }
          }
        }
      }
    },
```

or if I just want to define the for a particular `method` for the `endpoint` also works. E.g for `/user` endpoint, there's `POST`, `GET`, etc. I can define just one of them and that would override whatever will be generated?

---

Thanks! I tried `definitions` before I posted, but I guess I must have typed the wrong syntax or something. I tried both and it works now.

**Comment by Mairu** [comment]
Yes, I meant to give the complete "method object" as you did in your example. And because this is not auto-generated there should not be the need to change it afterward?

To specify this object in paths manually should only be used when it will not be generated automatically.

I don't know if I got your question tbh.

**Comment by bwgjoseph** [comment]
Sorry for the confusion. I wasn't thinking through.

I was thinking in the context of `authentication` but forgot that you mentioned that because `authentication` is registered internally, hence, I can't change it.

By default, `authentication` only generate for `/POST` and `/DELETE` endpoint, and both does not requires `bearer token`. I wanted to see if I could override it, and set 

```
delete: {
          security: [{
            BearerAuth: []
          }],
        }
````

for `authentication /DELETE` endpoint. 

As for the rest of the services, I could override them inside the `service.docs` portion as those are not registered internally, hence I could override it. Correct me if I'm wrong. For example, in `user.service.ts`.

```
cService.docs = {
    description: 'Service to manage user',
    // Can use all or define individual method type
    securities: ['all'],
    schemas: {
      userResponse: {
        type: 'object',
        properties: {
          a: { type: 'number' },
          b: { type: 'string' },
          start_date: { $ref: 'common.json#/definitions/ISODateFormat' },
        }
      }
    },
    operations: {
      find: {
        'responses.200': {
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/userResponse'
              }
            }
          }
        },
        'security': [],
      }
    }
  };
```

Although, it didn't really make sense to override `security` here in `find`, but I'm just making a point.

I guess this should covers it. 

Once again, thank you for your assistance.

**Comment by Mairu** [comment]
Yes, that is possible.

Where it could make sense is, if you have multiple authentication methods like in this example. https://github.com/feathersjs-ecosystem/feathers-swagger/blob/master/example/openapi-v3/security.js for

**Comment by bwgjoseph** [comment]
Yup, that does make sense. 

Thanks!

**Comment by viking225** [comment]
> Did you mean that I have to provide the entire `path` definition for the particular endpoint?
> 
> ```
> "paths": {
>     "/authentication": {
>       "post": {
>         "parameters": [],
>         "responses": {
>           "201": {
>             "description": "created",
>             "content": {
>               "application/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/authentication"
>                 }
>               }
>             }
>           },
>           "401": {
>             "description": "not authenticated"
>           },
>           "500": {
>             "description": "general error"
>           }
>         },
>         "description": "Creates a new resource with data.",
>         "summary": "",
>         "tags": ["authentication"],
>         "security": [],
>         "requestBody": {
>           "required": true,
>           "content": {
>             "application/json": {
>               "schema": {
>                 "$ref": "#/components/schemas/authentication"
>               }
>             }
>           }
>         }
>       }
>     },
> ```
> 
> or if I just want to define the for a particular `method` for the `endpoint` also works. E.g for `/user` endpoint, there's `POST`, `GET`, etc. I can define just one of them and that would override whatever will be generated?
> 
> Thanks! I tried `definitions` before I posted, but I guess I must have typed the wrong syntax or something. I tried both and it works now.

Hi @bwgjoseph  do you got the request body for this configuration in UI ? I did try this one and a bunch of other ones and i cannot get the requestBody to print when in "specs.paths" config

**Comment by bwgjoseph** [comment]
Yes I do.

This is my current setup.

![image](https://user-images.githubusercontent.com/37484538/62478290-484a6000-b7dd-11e9-99a5-57bc5d1d42ba.png)

I register swagger before authentication.

This is the UI.

![image](https://user-images.githubusercontent.com/37484538/62478316-5bf5c680-b7dd-11e9-9457-befe687a90ae.png)

**Comment by viking225** [comment]
Hum @bwgjoseph  sorry but i checked again, but i can't get it to work with your configuration (I raw copied just to be sure) and i didn't find enough documentation on the path attributes for feathers-swagger.

I disabled the default authentication by passing in the ignore attribute during swagger init.
I can get the responses code in my UI but no request attributes or response body. I'll copy my config just below, does it bother you to tell me if you spot some differences whith yours ? (i don't)
 
```js
  app.configure(swagger({
    specs: {
      info: config.info,
      paths: {
        '/authentication': {
          post: {
            summary: 'Get new JWT',
            description: 'Get new JWT to access restricted routes on api thanks to user info',
            responses: {
              201: {
                description: 'JWT returned',
                "content": {
                  'application/json': {
                    type: 'object',
                    properties: {
                      accessToken: {
                        type: 'string',
                        description: 'Token used to access restricted resource'
                      },
                      expiresIn: {
                        type: 'string',
                        description: 'Expiration date of the token'
                      }
                    }
                  }
                }
              },
              401: {
                description: 'Unauthorized'
              }
            },
            requestBody: {
              description: 'User information for login',
              required: true,
              content: {
                'application/json': {
                  schema: {
                    $ref: '#/components/schemas/userAuthentication'
                  }
                }
              },
            },
          },
        }
      },
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT'
          }
        },
        schemas: {
          peoples: {
            type: 'object',
            properties: peoplesSchema.properties
          },
          userAuthentication: {
            type: 'object',
            properties: {
              userName: {
                type: 'string',
                description: 'Username used to log in'
              },
              password: {
                type: 'string',
                description: 'Password for the specific user'
              }
            }
          }
        }
      },
    },
    docsPath: config.url,
    ignore: config.ignore,
    uiIndex: true
  }));

```

And this is my UI : 
![image](https://user-images.githubusercontent.com/10079913/62607849-0d404d80-b8ff-11e9-94c1-39e8bc437587.png)

**Comment by bwgjoseph** [comment]
This is the entire config.

```javascript
app.configure(swagger({
  openApiVersion: 3,
  idType: 'string',
  docsPath: '/docs',
  docsJsonPath: '/jsondocs',
  uiIndex: true,
  specs: {
    info: {
      title: 'API',
      description: 'API',
      version: '1.0.0',
    },
    servers: [
      {
        url: 'http://localhost:3030',
        description: 'Production server (uses live data)',
      },
      {
        url: 'http://sandbox-api.example.com:8443/v1',
        description: 'Sandbox server (uses test data)'
      },
      {
        url: 'http://{environment}.local:3030',
        description: 'Production server (uses live data)',
        variables: {
          environment: {
            enum: ['dev', 'staging', 'production'],
            default: 'dev',
          }
        }
      },
    ],
    components: {
      securitySchemes: {
        BearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT'
        }
      },
      schemas: {
        userAuthentication: {
          type: 'object',
          properties: {
            userName: {
              type: 'string',
              description: 'Username used to log in'
            },
            password: {
              type: 'string',
              description: 'Password for the specific user'
            }
          }
        },
        userAuthenticationResponse: {
          type: 'object',
          properties: {
            accessToken: {
              type: 'string',
              description: 'Token used to access restricted resource'
            },
            expiresIn: {
              type: 'string',
              description: 'Expiration date of the token'
            }
          }
        }
      }
    },
    paths: {
      '/authentication': {
        post: {
          summary: 'Get new JWT',
          description: 'Get new JWT to access restricted routes on api thanks to user info',
          responses: {
            201: {
              description: 'JWT returned',
              content: {
                'application/json': {
                  schema: {
                    $ref: '#/components/schemas/userAuthenticationResponse'
                  }
                }
              }
            },
            401: {
              description: 'Unauthorized'
            }
          },
          requestBody: {
            description: 'User information for login',
            required: true,
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/userAuthentication'
                }
              }
            },
          },
        },
      }
    },
    security: [{
      BearerAuth: []
    }],
  },
  ignore: {
    paths: ['authentication']
  },
  defaults: {
    schemasGenerator(service, model, modelName) {

      return {
        [model]: service.model,
        [`${model}_list`]: {
          title: `${modelName} list`,
          type: 'array',
          items: { $ref: `#/components/schemas/${model}` }
        },
      };
    },
  }
}));
```
This is the result based on the definition above.

![image](https://user-images.githubusercontent.com/37484538/62776109-34a04180-badc-11e9-8372-7b9028e48d30.png)

I defined the response (userAuthenticationResponse) as a schema definition on top. Then use it at `201 response` below, rather than defining it together.

Hope it helps.

**Comment by josepcrespo** [comment]
Currently, it's much more simple: just put your definition on your `authentication.js` or `authentication.ts` file:

Currently, it's much more simple: just put your definition on your `authentication.js` or `authentication.ts` file:

`// Content of ./src/authentication.js
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { LocalStrategy } = require('@feathersjs/authentication-local');
const { expressOauth, OAuthStrategy } = require('@feathersjs/authentication-oauth');

class GitHubStrategy extends OAuthStrategy {
  async getEntityData(profile) {
    const baseData = await super.getEntityData(profile);

    return {
      ...baseData,
      // The user email address (if publicly available)
      email: profile.email
    };
  }
}

module.exports = app => {
  const authentication = new AuthenticationService(app);

  authentication.register('jwt', new JWTStrategy());
  authentication.register('local', new LocalStrategy());
  authentication.register('github', new GitHubStrategy());

  // The Swagger definition.
  authentication.docs = {
    description: 'Service to manage authentication.',
    definitions: {
      authentication: {
        type: 'object',
        required: ['strategy'],
        properties: {
          strategy: {
            type: 'string',
            enum: ['jwt', 'local', 'github'],
            example: 'local',
            description: 'Type of strategy used to validate the user credentials.'
          },
          email: {
            type: 'string',
            example: 'hello@emailprovider.com'
          },
          password: {
            type: 'string',
            example: '1qazxsw23edcvfr4'
          }
        }

      }
    }
  };

  app.use('/authentication', authentication);
  app.configure(expressOauth());
};`

**Comment by Mairu** [comment]
True, with feathers v4 the authentication service can be modified like any other service which was not the case for feathers v3.

**Comment by bwgjoseph** [comment]
You are right if I ignore typings for `typescript`, no issue if you're using `javascript`

I would have to do `(authentication as any).docs`.

What I did was to extend `AuthenticationService` and implements `ServiceSwaggeraddon`.

```js
class CustomAuthenticationService extends AuthenticationService implements ServiceSwaggerAddon {
  docs: ServiceSwaggerOptions = {
    description: 'Service to manage Authentication',
    definitions: {
      authentication: requestSchema,
      authenticationResponse: responseSchema,
    },
    operations: {
      create: {
        'responses.201.content.application/json.schema.$ref':
          '#/components/schemas/authenticationResponse',
      },
      remove: false,
    },
  };
}
```
