### ISSUE TITLE
filter object not displaying

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs-ecosystem/feathers-swagger#160]
Hi,

With reference to issue #155, my current `filter object` does not show in the `UI`. I don't think I have made any changes. 

![image](https://user-images.githubusercontent.com/37484538/61888890-f41ac280-af36-11e9-8339-ba1bbef7b5ed.png)

The following are my configuration.

```
app.configure(swagger({
  openApiVersion: 3,
  idType: 'string',
  docsPath: '/docs',
  docsJsonPath: '/jsondocs',
  uiIndex: true,
  specs: {
    info: {
      title: 'API',
      description: 'API',
      version: '1.0.0',
    },
    servers: [
      {
        url: 'http://localhost:3030',
        description: 'Production server (uses live data)',
      },
    ],
  },
  defaults: {
    schemasGenerator(service, model, modelName) {
      return {
        [model]: service.model,
        [`${model}_list`]: {
          title: `${modelNameCapitalized} list`,
          type: 'array',
          items: { $ref: `#/components/schemas/${model}` }
        },
      };
    }
  }
}));
```

In `user.service`

```
const cService = createService(options);

  cService.model = user.schema;

  cService.docs = {
    description: 'Service to manage user',
    // Can use all or define individual method type
    securities: ['all'],
  };

  app.use('/user', cService);
```

User schema.

```
let schema = {
  // !<DEFAULT> code: schema_header
  title: 'User',
  description: 'User database.',
  // !end
  // !code: schema_definitions // !end
  type: 'object',
  // Required fields.
  required: [
    // !code: schema_required
    'email',
    'firstName',
    'lastName',
    'password'
    // !end
  ],
  // Fields in the model.
  properties: {
    // !code: schema_properties
    email: { type: 'string' },
    firstName: { type: 'string' },
    lastName: { type: 'string' },
    password: { type: 'string' },
    // !end
  },
  // !code: schema_more // !end
};
```

No error on the top of swagger UI page, nothing obvious that I can see.

I'm still serving my `common.json` correctly.

Any pointers?

Thanks.

**Comment by Mairu** [comment]
The first thing what you should do when something does not work correctly.
Open the Swagger Editor (https://editor.swagger.io/ or host it locally) and paste the contents of you the generated json. ( docsJsonPath ).
Then the editor will tell you all errors that you have in the specification.

modelNameCapitalized is never defined, but this should not be the problem.

**Comment by bwgjoseph** [comment]
Sorry, my mistake. `modelNameCapitalized` is actually just `modelName`.

I did use my locally hosted Swagger Editor and pasted the json but couldn't see what's wrong with it.

So for example, I have this `userResponse` defined.

![image](https://user-images.githubusercontent.com/37484538/61967978-5e039c80-b009-11e9-9b8c-1a80c7c371e7.png)

I have to manually change to add `domain` to `common.json` because swagger-editor was hosting at another port (7000) to be able to resolve it.

![image](https://user-images.githubusercontent.com/37484538/61968134-ce122280-b009-11e9-8fd2-8088c58f3543.png)

---

So I have my user definition defined..

![image](https://user-images.githubusercontent.com/37484538/61968380-7a540900-b00a-11e9-94cb-f17331e2fd57.png)

User operation...

![image](https://user-images.githubusercontent.com/37484538/61968424-92c42380-b00a-11e9-9806-8effae61c0f6.png)

Filter operation...

![image](https://user-images.githubusercontent.com/37484538/61968439-9fe11280-b00a-11e9-8b9f-ee999cdb9263.png)


I can't figure out what's wrong with it. As you can use, the response 200 is showing the `userResponse` object.

So if I were to try to change things a little, just to see if it would appear in the `filter`..

So for the `filters`, I change to use `userResponse` instead of `user.

![image](https://user-images.githubusercontent.com/37484538/61968687-38779280-b00b-11e9-923c-492bdcc00c3d.png)

But the UI is still not showing..

![image](https://user-images.githubusercontent.com/37484538/61968709-45948180-b00b-11e9-9bd7-476747e01c4d.png)

Do let me know what I have missed out. Thanks!

**Comment by Mairu** [comment]
So this has changed with Swagger-UI Version 3.23.
Possible solutions:
- fix installation version of swagger-ui-dist to 3.22.3
- add an example to your schema, this will be used by versions >= 3.23

I don't know if you want to create an issue for Swagger UI, for me this seems to be a regression of 3.23.

**Comment by bwgjoseph** [comment]
Hi,

How do I fix the `swagger-ui-dist` version? It comes with `feathers-swagger` right? I'm using `uiIndex: true` where it will grab from `node_modules`. However, the last time I tried and it works, I am also using `feathers-swagger` v1.1.0, so what change? Anything I missed out?

Unfortunately, I have added in example in my schema, but it does not show as well.

![image](https://user-images.githubusercontent.com/37484538/62381363-e3dd9580-b57d-11e9-859b-30710ede463a.png)

![image](https://user-images.githubusercontent.com/37484538/62381381-edff9400-b57d-11e9-924c-2e790b817226.png)

> I don't know if you want to create an issue for Swagger UI, for me this seems to be a regression of 3.23.

Will probably do so.

**Comment by Mairu** [comment]
You can add swagger-ui-dist with a specific version to your dependencies. This will "overrule" the one from feathers-swagger.

For the example, this has to be given as whole object.
```
  // Fields in the model.
  properties: {
    // !code: schema_properties
    email: { type: 'string' },
    firstName: { type: 'string' },
    lastName: { type: 'string' },
    password: { type: 'string' },
    // !end
  },
  // !code: schema_more // !end
  example: {
    email: 'abc@def.com',
    fistName: 'hans',
    lastName: 'muller',
    password: 'secure-hash'
  }
```

**Comment by bwgjoseph** [comment]
Thanks, it works.

So I went to did some reading, so it has been in OpenApi v3 for some time, just that the `swagger-ui` only made the changes to support it recently with `v3.23.0` onwards.

I think I agree with you. Since `3.23.0`, they added support for `examples` object but it shouldn't break the current one? Will open a issue and see how it goes.
