### ISSUE TITLE
remove field from specific operation call

### ISSUE THREAD

**Issue by bwgjoseph** [feathersjs-ecosystem/feathers-swagger#161]
Hi,

I am wondering if it is possible to override the default schema generation, and at the `service.docs` remove certain fields to display in the `example` portion?

My schema is as such.

![image](https://user-images.githubusercontent.com/37484538/61891560-807bb400-af3c-11e9-95f8-fad5e6b8c19a.png)

And the `example` in `POST` ops will be as such.

![image](https://user-images.githubusercontent.com/37484538/61891610-98533800-af3c-11e9-976f-316addd66d2b.png)

I would like to remove `_id`, `createdAt`, `updatedAt`, and `_v` from the `example` as those are values generated by database. If it is showing there, user may be mistaken that those values are required to be submitted during the `POST` ops.

So it would be as such.

![image](https://user-images.githubusercontent.com/37484538/61892148-c84f0b00-af3d-11e9-8c06-cbc47d4a2809.png)

Thanks.

---

Also wondering if it is a common practice to expose all these fields at all? Assuming that all these are for internal consumption only. So that it only show as such.

![image](https://user-images.githubusercontent.com/37484538/61892059-9473e580-af3d-11e9-8ff0-6f9743ec887f.png)

**Comment by Mairu** [comment]
What fields you want to be shown on the page is completely up to you. You define the schema.

You can define as many different schemas as you want. And use the different schemas for the different methods. You can specify that in the **refs** option of the service.

**Comment by bwgjoseph** [comment]
Thanks, `refs` was the key to it. 

I was initially thinking if I could just define somewhere to exclude some fields. But looks like defining another `definitions` and passing to `refs` is the way to go.

**Comment by Mairu** [comment]
As a side note if you need an object only once you don't have to create a reference for it but could directly define it docs.operations wherever you need it.

**Comment by bwgjoseph** [comment]
Sorry, I don't quite get it. Any simple example to go along with it? 

Thanks.

**Comment by Mairu** [comment]
Nothing special, I just meant you could set the request/response etc. directly in the operations option of the service without using references.

e.g.
```
service.docs = {
   operations: {
     create: {
       'requestBody.content': {
         type: 'object',
         properties: { ... }
       }
     }
   }
}
```

**Comment by bwgjoseph** [comment]
I was trying that initially, but couldn't quite get it format right. 

So it was in `requestBody.content`.

Thanks for the tip!
