### ISSUE TITLE
Nested resources shown in wrong group

### ISSUE THREAD

**Issue by MStumpp** [feathersjs-ecosystem/feathers-swagger#162]
When adding nested resources according to https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes

The nested resource is grouped with the upper level resource instead of lower level resource. Considering the example shown in faq, i would expect seeing the nested resource "post" in group "posts" instead of "users".

**Comment by Mairu** [comment]
This is not a bug.

The grouping is done based on the tags of a service.
If you don't define the tag yourself it will be automatically generated from the path the service is registered at. ( https://github.com/feathersjs-ecosystem/feathers-swagger/blob/master/lib/openapi.js#L67 )

You have multiple options:
 - define the tag in the options of the service (service.docs.tag = 'posts')
 - define your custom getOperationArgs ( in defaults options of the init function ) if you have many of such nested services.  (You only have to return the the things you want to change from the default, in your case tag)
