### ISSUE TITLE
What would be the easiest way to add a unique operationId?

### ISSUE THREAD

**Issue by nuc** [feathersjs-ecosystem/feathers-swagger#166]
Hi there,

I'm trying to add a unique `operationId`, in the form of `[serviceName].[method]`?

I've tried to define the `operationGenerators`, but I think that they don't support merging, so I wouldn't want to have to define all the props for all methods.

I also tried the static `operations[method]`, but I don't know if it's possible to use a dynamic value in there.

What would be the easiest way to define such a property?

Thank you in advance,
Georgios

**Comment by Mairu** [comment]
Hi,

I am sorry, but I don't understand what you mean by operationId. If you mean the id used in the path for GET, UPDATE, etc. requests, there is an option idNames. This is on the service level only.

If you mean something else please show the specification you want to achieve.
