### ISSUE TITLE
Bug: Cannot Overwrite Schemes when uiIndex = true

### ISSUE THREAD

**Issue by wipro-ivan** [feathersjs-ecosystem/feathers-swagger#167]
(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs-ecosystem/feathers-swagger/blob/master/.github/contributing.md#report-a-bug))

**Describe the bug**
When using feathers-swagger with uiIndex set to true (automatic generation of swagger documentation), I try to set my schemes in my app.js swagger configuration by adding schemes:['http','https'] to the config data. However this doesn't apply to the documentation.

**To Reproduce**
`app.configure(swagger({
    docsPath: '/docs',
    uiIndex: true, //no need for src/docs.html to be included
    info:{
        title:'*** API',
        description:'Swagger documentation for **** API'
    },
    ignore:{
        tags:['authentication']
    },
    schemes:['http','https']
}`

Then refresh app and go to basepath/docs, only HTTP shows: 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/32336786/65032609-627a7080-d93b-11e9-97fa-371445542ee5.png">

**Expected behavior**
I refresh my app go to basepath/docs and see HTTP and HTTPS in the swagger documentation site schemes dropdown
**System configuration**
 - Package versions: [e.g. feathers-swagger 1.1.0, @feathersjs/configuration 2.0.6, @feathersjs/feathers 3.3.1 ]
 - NodeJS version: 10.16.0
 - Mac OS

**Additional context**

**Comment by Mairu** [comment]
Well the 'to reproduce' code is really not well-formatted, but It looks like a config for feathers-swagger before version 1.0.

For feathers-swagger >= 1.0 you have to put your specification related changes into a specs property of the config.

```
app.configure(swagger({
  docsPath: '/docs',
  uiIndex: true,
  //no need for src/docs.html to be included
  specs: {
    info:{ title:'*** API', description:'Swagger documentation for **** API' },
    schemes:['http','https']
  },
  ignore:{ tags:['authentication'] }
}
```

**Comment by wipro-ivan** [comment]
> Well the 'to reproduce' code is really not well-formatted, but It looks like a config for feathers-swagger before version 1.0.
> 
> For feathers-swagger >= 1.0 you have to put your specification related changes into a specs property of the config.
> 
> ```
> app.configure(swagger({
>   docsPath: '/docs',
>   uiIndex: true,
>   //no need for src/docs.html to be included
>   specs: {
>     info:{ title:'*** API', description:'Swagger documentation for **** API' },
>     schemes:['http','https']
>   },
>   ignore:{ tags:['authentication'] }
> }
> ```

Thank you so much! Yeah you're right about me using an old version of code, I got that feathers swagger config code from a code snippet that was in an issue from a while back. 

I used your method and it worked perfectly

**Comment by wipro-ivan** [comment]
Not a bug
