### ISSUE TITLE
Bug: feathers 4.x compatibility

### ISSUE THREAD

**Issue by craigharman** [feathersjs-ecosystem/feathers-swagger#179]
I have installed the package and can see the swagger json at /docs, but adding ```uiIndex: true``` does not produce the swagger-ui html at /docs.

**To Reproduce**
Fresh install of feathers 4 (using cli).
In app.js add:

```
const swagger = require('feathers-swagger'); 
````

then during configuration:

```
// Configure swagger
app.configure(swagger({
  specs: {
    docsPath: '/docs',
    uiIndex: true,
    info: {
      title: 'A test',
      description: 'A description',
      version: '1.0.0',
    },
  }
}));
```

**Expected behavior**
Going to http://localhost:3030/docs should display Swagger UI

**System configuration**
 - Package versions:feathers-swagger 1.1.0, @feathersjs/feathers 4.4.1
 - NodeJS version: [e.g. 12.7.0]
 - OS Mac OS X

**Comment by Mairu** [comment]
You put the options into the specs property.

```// Configure swagger
app.configure(swagger({
  docsPath: '/docs',
  uiIndex: true,
  specs: {
    info: {
      title: 'A test',
      description: 'A description',
      version: '1.0.0',
    },
  }
}));
```
