### ISSUE TITLE
Multi file upload not working

### ISSUE THREAD

**Issue by dangxquang** [feathersjs-ecosystem/feathers-swagger#200]
I defined a route with multipart/form-data file upload.
``` Javascript
uploads.docs = {
    description: 'A service to upload files',
    externalDocs: {
      description: 'Swaggers',
      url: 'https://github.com/feathersjs-ecosystem/feathers-swagger',
    },
    model: 'Uploads',
    tag: 'Uploads',
    operations: {
      find: false,
      get: false,
      update: false,
      remove: false,
      patch: false,
      create: {
        description: 'Upload files',
        requestBody: {
          content: {
            'multipart/form-data': {
              schema: {
                type: 'object',
                properties: {
                  files: {
                    type: 'array',
                    items: {
                      type: 'string',
                      format: 'binary'
                    }
                  }
                },
              },
            },
          },
        },
      },
    },
  }
```
But the form-data is not correct with CURL:
`curl -X POST "http://localhost:3030/v1/uploads" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "file=[object File]"`
![image](https://user-images.githubusercontent.com/49668846/79773869-2fc6a980-835c-11ea-92f7-ed547e73d85b.png)

Does anyone success with multiple files upload?
Sorry for my poor english

**Comment by Mairu** [comment]
Hi,
I have not worked with file uploads yet.
But this "problem" is only related to [swagger-ui](https://swagger.io/tools/swagger-ui/) and [swagger specification](https://swagger.io/docs/specification/describing-request-body/file-upload/).

Your definition looks correct.

As by default an old version of swagger-ui is used, you should try to use swagger-ui as a direct dependency of your project, to use the current version. If the problem still occurs, you should ask the swagger-ui people.
