### ISSUE TITLE
GitHub sponsorship from the OpenCollective

### ISSUE THREAD

**Issue by daffl** [feathersjs-ecosystem/feathers-swagger#216]
Thank you @Mairu for keeping this repository maintained. I would be happy to start sponsoring some of your work through the [Feathers OpenCollective](https://opencollective.com/feathers) starting with a 50$/month [GitHub sponsor](https://github.com/sponsors) tier. If you are interested let me know once you are signed up for GitHub sponsors and have the tier set up.

**Comment by Mairu** [comment]
Hi @daffl, thanks for the appreciation but currently I shun the bureaucratic effort that would be needed.

**Comment by daffl** [comment]
I am well aware of the pains the German Finanzamt can put its "customers" through. For me living in Canada it took less than 30 minutes to get it all set up and get deposited into my bank account automatically. Anyway, let me know if you change you rmind.
