### ISSUE TITLE
Two DocPaths for separate API groups

### ISSUE THREAD

**Issue by khazig88** [feathersjs-ecosystem/feathers-swagger#229]
Hi,

Is there a way to separate two API groups into different doc paths (e.g. /docs and /docs-v2)? I'm currently using redoc in my docs.html in order to host my docs, but would like a separate doc path for a different API group. 

Thanks in advance.

**Comment by Mairu** [comment]
I have not tested it, but it could be possible by initializing feathers-swagger 2 times with different options.

It would be important to use either `include` and/or `ignore` to specify the paths for the different versions, and then use the options `docsPath` (, `docsJsonPath`) and `appProperty` to have different versions.

**Comment by Mairu** [comment]
The examples of this repo also are kind of separated API groups.

**Comment by khazig88** [comment]
Thanks! Initializing feathers-swagger again worked.
