### ISSUE TITLE
docs ignored when path already exists

### ISSUE THREAD

**Issue by psi-4ward** [feathersjs-ecosystem/feathers-swagger#23]
Version: 0.3.1

// Service definiton
```javascript
module.exports = function(){
  const app = this;
  const db = new NeDB(...);
  // ...
  app.use('/projects/:projectId/sync', projectsSyncService);
  
  const docs = { description: 'My Project Service' }
  app.use('/projects', Object.assign(service(options), { docs }) );
```

The first `app.use` spawns the `projects` tag in the spec and the docs definition from `app.use('/projects'` gets ignored by 
https://github.com/feathersjs/feathers-swagger/blob/master/src/index.js#L220

The workaround is add the docs to the very first use but it's way confusing and the sub-service should hold its own docs. Probably we should use the group-defs only for first-level paths or merge the defs?

**Comment by Mairu** [comment]
Introduced overwriteTagSpec option for service.docs config object to handle the behavior in version 1.0.0
