### ISSUE TITLE
Bug: Can't access ID in path

### ISSUE THREAD

**Issue by AshotN** [feathersjs-ecosystem/feathers-swagger#246]
**Describe the bug**
The typing for the custom method doesn't expose `params` which contains the `id` in the path.

**To Reproduce**
```
  @customMethod('GET', '/:id/download')
  async download(data: any, params: Params) {
    const id = params.params.id; // <-- TS error
  }
```

![image](https://user-images.githubusercontent.com/1350342/199131250-9536333a-2c4f-4b76-aa71-d81c2f20b0bf.png)

**Expected behavior**
The typing should contain `params` as an exposed property, or provide another means to retrieve the ID.

**System configuration**
```
 "feathers-swagger": "^3.0.0-pre.0",
 "@feathersjs/feathers": "^5.0.0-pre.32",
```

**Additional context**
`data` is also `undefined` if it matters

**Comment by Mairu** [comment]
The typing of feathers method params is not in the hands of the library.

You can adjust the typing of params in the `declarations.ts` file of your project. As example, the generator also adds the user object to the params interface.

```
// Add the user as an optional property to all params
declare module '@feathersjs/feathers' {
  interface Params {
    user?: UsersResult;
    params?: Record<string, string>;
  }
}
```

> `data` is also `undefined` if it matters
Data should be only defined if provided to the REST call when using a method that supports data (POST, PUT, PATCH). For a GET call it should always be undefined.

**Comment by AshotN** [comment]
Thanks for the help!
