### ISSUE TITLE
Feature: Handle Type.Literal

### ISSUE THREAD

**Issue by AshotN** [feathersjs-ecosystem/feathers-swagger#247]
**Is your feature request related to a problem? Please describe.**
`Type.Literal` from [TypeBox](https://dove.feathersjs.com/api/schema/typebox.html#literal)  gets treated as the underlying type of the value.

**Describe the solution you'd like**
`Type.Literal` should show up as the value

A property defined like this `type: Type.Literal('company')` shows up as `"type": "string"` instead of what I would expect as `"type": "company"`

**Comment by Mairu** [comment]
Hi, I don't know what you expect but TypeBox is creating the json schema, not feathers-swagger.

Also there is nothing like a type "company", there is a very limited set of types: https://spec.openapis.org/oas/latest.html#data-types.

Please check https://github.com/sinclairzx81/typebox#standard-types to see what JsonSchema output you can expect when using TypeBox.

If you describe your goal, I can perhaps guide you into the right direction.

**Comment by AshotN** [comment]
`company` in this example is not a type, `Type.Literal` is like allows you to define a static value for the property. Perhaps the names I chose for the variables were confusing.

Hopefully this is a more clear example of usage of `Type.Literal`
```
const myObject: TObject<{myLiteralValue: TLiteral<"aRandomString!">}> = Type.Object({
  myLiteralValue: Type.Literal('aRandomString!'),
})
```

**Comment by daffl** [comment]
JSON schema does not have custom types, `type` can only be the ones from the [list here](https://json-schema.org/understanding-json-schema/reference/type.html).

So `Type.Literal` will have the `type` the literal you passed (`string`, `number` or `boolean`). Another example can be found at https://dove.feathersjs.com/api/schema/typebox.html#literal

**Comment by AshotN** [comment]
My suggestion is to use the `const` value instead of the type in the example schema. 

![image](https://user-images.githubusercontent.com/1350342/201806904-8bf40768-f805-476b-b433-916df7ca13f0.png)

![image](https://user-images.githubusercontent.com/1350342/201806811-049fac45-13cd-45f5-9583-aab4ac4cf078.png)

**Comment by Mairu** [comment]
You could add the example to the options parameter of the typebox types -> https://github.com/sinclairzx81/typebox#options

`type: Type.Literal('company', { example: 'company' })`

If you want to automate this somehow you could use the `sanitizeSchema` option of `createSwaggerServiceOptions` function to adjust schemas as you like.

But I would not want to add such customizations to the library.
What are your thoughts @daffl?

**Comment by daffl** [comment]
I agree. We learned from experience that adding non-standard customisations like this can often cause other unforeseen problems with things not behaving like people (or other plugins) would expect.

**Comment by AshotN** [comment]
Fair enough.
