### ISSUE TITLE
How can I get correct prefix with $ref in related models?

### ISSUE THREAD

**Issue by skilltryck** [feathersjs-ecosystem/feathers-swagger#250]
I have spent a few days now trying to get feathers-swagger@pre working with related models using Type.Ref()

Can't seem to find any way to use correct prefix for $ref.
It always ends up as "[Model]" but seems to me it should be "#/components/schemas/[Model]".

Can someone point me in the right direction on how to fix this?

**Comment by Mairu** [comment]
Hi, I am sorry that I have not found the time to finish the new release yet.
I was experimenting with extending the sanitizeSchema function to replace the refs with working ones.

You can see what I have tired in https://github.com/feathersjs-ecosystem/feathers-swagger/blob/wip_3.0/lib/utils.js#L76
As this is then more than sanitizing in the end I think I will rename the parameter for the final version to something like transformSchema.

**Comment by skilltryck** [comment]
Thanks!
I will take a look at your example and try to implement that as my own sanitizeSchema function.
