### ISSUE TITLE
Feature Idea: Validation

### ISSUE THREAD

**Issue by arddor** [feathersjs-ecosystem/feathers-swagger#26]
I just stumbled upon [swagger-validate](https://github.com/signalfx/swagger-validate) and found that this would actually be a great thing if `feathers-swagger` would come with a hook for validation, which can validate based on swagger.

**Comment by eddyystop** [comment]
We are writing a hook which validates JSON objects using ajv. Ajv uses [json-schema](http://json-schema.org/) definitions.

Would that be suitable in this case?

**Comment by daffl** [comment]
I think so. Swagger uses JSON schema for its definitions as well.

**Comment by Brian-McBride** [comment]
Was there ever a connection with a validation hook to use the swagger definition?

**Comment by daffl** [comment]
The [validateSchema](https://feathers-plus.github.io/v1/feathers-hooks-common/#validateschema) common hook can be used for this now.
