### ISSUE TITLE
Where to set security scheme to enable auth token to be sent

### ISSUE THREAD

**Issue by Morriz** [feathersjs-ecosystem/feathers-swagger#36]
Just a question

**Comment by Morriz** [comment]
I have now got it working with auth, through trial and error, like this:

In the `{service}/index.js` file I have this section:

```
const _service = service(options);
  _service.docs = {
    securities: ['create', 'update', 'patch', 'remove']
  };
  app.use('/activity', _service);
```

but this seems redundant, as that information is given by setting the `restrictToAuthenticated` hooks. Can those calls not 'inflect' where they come from and set this information automatically?

**Comment by daffl** [comment]
Not at the moment since hooks don't add any additional information in to the service. Another way might be to set it globally as done in the Sequelize example in https://github.com/feathersjs/feathers-swagger/blob/master/example/sequelize/app.js#L52-L63

**Comment by idealley** [comment]
I got the security to work for the documentation as follow:

in `app.js` I configure swagger (in a module to simplify the code):

```
   const swOptions = require('./swagger/swagger');
   ...
   app.use()
   ...
  .configure(swagger(swOptions))
```

The module is configured as follow:

```
module.exports = {
    docsPath: '/docs',
    uiIndex: path.join(__dirname, 'docs.html'),
    info: {
      title: 'Title of the Documentation',
      description: 'Available endpoints'
    },
    securityDefinitions: {
      bearer: {
        type: "apiKey",
        name: "authorization",
        in: "header"
      }
    },
    security: [
      {
        bearer: []
      }
    ]
};
```

You need to set the 'securityDefinisions' and the `security` array as far as I am using the default authorization of feathers I need to say that I will be sending a `bearer` token. I define what is the bearer for the swagger UI to be able to generate the correct buttons (authorize one).

<img width="1004" alt="screen shot 2017-03-22 at 09 31 43" src="https://cloud.githubusercontent.com/assets/917006/24188661/8f329042-0ee2-11e7-8bdc-8515f91aeba3.png">

Then __per service__ I can now set __per route__ if this route needs authorization or not. So when you instantiate a service, you need:

```
  // Initialize our service with any options it requires
  app.use('/users', Object.assign(service(options), {
      docs: def
    })); 
```

I am passing a definition which allows: custom description of the endpoint, to add params definition, examples etc.

For example if you want to limit a create route to authorized users: 

```
module.exports = {
  description: 'Users of the API (requires administrator role)',
  find: {
  },
  get: {
  },
  create: {
    security: [    {
      bearer: []
    }]
  },
  update: {
  },
  patch: {
  },
  remove: {
  }
};
```
As far as security is an array you can pass it other security strategies and of course you can pass other objects for each method here is another example with method definition:

```
const params = require('./parameters');

module.exports = {
    security: [    {
      bearer: []
    }],
  description: 'ERS Articles',
  find: {
    description: 'Get articles relative to a node with the node', 
    summary: 'Returns the category (node) and its outgoing relatives with the association ers:article',parameters: [
        params.qname,
        params.limit,
        params.skip
    ],
    responses: {
      "200": {
            description: 'successful operation',
            schema: {
              type: "object",
              example:
                {
                    "data": [],
                    "category": [],
                    "_sys": {
                        "next": 'string',
                        "prev": 'string'
                    },
                    "limit": 'int',
                    "skip": 'int',
                    "total": "coming soon"
                }
              
            },
      },
      "404": {
            description: 'not found',
            schema: {
              type: "string"
            }
      }
    },
    produces: ["application/json"]
  }
};
```

I have externalised the params as I need to reuse the same one on other services.

I hope this configuration may help someone ;) as it did not work right away... some trial and error involved...

**Comment by Mairu** [comment]
Example of authentication configuration was added to the repository.

**Comment by gauravbhusare** [comment]
I am not able to get taht authorize button on top
![image](https://user-images.githubusercontent.com/20472198/70619868-e347c080-1c3b-11ea-935c-ae989aeb60af.png)

I have added 
`securityDefinitions: {
      bearer: {
        type: "apiKey",
        name: "authorization",
        in: "header"
      }
    },
    security: [
      {
        bearer: []
      }
    ]`
 above code.

**Comment by Mairu** [comment]
See https://github.com/feathersjs-ecosystem/feathers-swagger/blob/master/example/swagger-v2/security.js for a working example.

You also have to define the securities for the services.

**Comment by gauravbhusare** [comment]
Thank you so much @Mairu
