### ISSUE TITLE
bug: resourceId not set as literal

### ISSUE THREAD

**Issue by Morriz** [feathersjs-ecosystem/feathers-swagger#37]
when a post/put/patch is done, the resourceId is not expanded, as the url contains dynamic ids, like {_id}, instead of always {resourceId}

I have fixed this by replacing line `lib/index.js:105` with:
```
    var withIdKey = '/' + path + '/{resourceId}';
```

Sorry, but I don't have the time right now to do a proper pull request.

**Comment by daffl** [comment]
You can make that change in the browser by editing the file at https://github.com/feathersjs/feathers-swagger/edit/master/src/index.js. GitHub then gives you the option to automatically create a pull request from it.
A pull request will help get this fix released significantly faster.

**Comment by Mairu** [comment]
Was fixed with https://github.com/feathersjs-ecosystem/feathers-swagger/pull/68
