### ISSUE TITLE
Work with Swagger Editor & YAMLconfig files

### ISSUE THREAD

**Issue by jerfowler** [feathersjs-ecosystem/feathers-swagger#59]
I wish this project were more like [swagger-node](https://github.com/swagger-api/swagger-node) where you can edit the swagger YAML in the [editor](http://swagger.io/swagger-editor/) then use feathers-cli to generate the services based on the YAML.

The editor is a great feature of the Swagger toolset and you really should write the specification for the API **before** you code it. 

So, instead of manually creating the doc property on each of the service objects, one would be created automatically based on the YAML specification created in the editor. The feather-cli would then be able to read the specification and then be able to tell with services needed to be created/modified/removed when the YAML file was changed in the editor. 

The feathers-cli would also generate test suites based on the YAML specification to make sure the services were implemented properly according to the specifications.

**Comment by Mairu** [comment]
The scope of this package is to generate documentation for feathers services. Not to create services from swagger / openapi specifications.

A package that creates services from yaml/json specifications is a completly different usecase and would not need anything from this package.
