### ISSUE TITLE
Automatic swagger conf

### ISSUE THREAD

**Issue by josx** [feathersjs-ecosystem/feathers-swagger#62]
Is there any feature to create swagger conf directly from the feathers API?

**Comment by christopherjbaker** [comment]
#68 did add some more intelligence to the default created docs, though it did not add any automatic docs. I think that would need to be integrated into each service type (ie: feathers-sequelize, feathers-elasticsearch, etc), as feathers itself does not know about the structure of the data. Personally, I do have a bit of code for my elasticsearch that generates docs based on the index mappings, though I did not integrate it into the feathers-elasticsearch module.

@daffl Would you be open to adding auto-generating docs to the individual modules when feathers-swagger is in use?

**Comment by jraut** [comment]
I have a snippet which generates swagger definitions from sequelize models which is run in service definitions. I am willing to participate if this is going forward.

**Comment by Mairu** [comment]
There is now the possibility to adjust the generation for different methods.
And also to generate definitions based on the service (and therefor the connected orm model).

There is space for other orm (or jsdoc) related packages, that create docs properties for services before services are consumed by feathers-swagger.
