### ISSUE TITLE
Using $ref

### ISSUE THREAD

**Issue by gpietro** [feathersjs-ecosystem/feathers-swagger#90]
Is it possible to use $ref with URI instead of definitions?

**Comment by gpietro** [comment]
I did manage to load refs from local files with [json-refs](https://github.com/whitlockjc/json-refs). The problem now is the Promise. json-refs returns a promise and in service.js it doesn't seem to be able to handle it.
What would be the best approach by loading the schema asynchronously?
Thanks

**Comment by Mairu** [comment]
The current version of Swagger UI support URIs from https://swagger.io/docs/specification/using-ref/.
This package is only creating json specs. There the uris should be strings and be handled by the consumer.
So all local referenced files have also to be served to be reachable (in the browser).
