### ISSUE TITLE
How to add the querying parameter to filter?

### ISSUE THREAD

**Issue by alinex** [feathersjs-ecosystem/feathers-swagger#93]
See [feathersjs Querying](https://docs.feathersjs.com/api/databases/querying.html) which uses additional parameters for each field but how to get it shown (like pagination) in swagger?

    GET /messages?read=false&roomId=2

This should be callable through swagger.

**Comment by alinex** [comment]
Also the possible `$select` parameter is missing in swagger.

How can I define this parameters for a service method?

**Comment by Mairu** [comment]
Parameters can be configured at mulitple levels with version 1.0.0. It it describes in the readme and some examples.

**Comment by askdesigners** [comment]
A link to the relevant place in the docs would be handy. 
The section about "Path support to update nested structures" is obtuse and not easy to understand.

**Comment by Mairu** [comment]
Example how to add a parameter: https://github.com/feathersjs-ecosystem/feathers-swagger/blob/master/example/openapi-v3/definitions.js#L66
