### ISSUE TITLE
generate documentation json from js docs

### ISSUE THREAD

**Issue by osman-mohamad** [feathersjs-ecosystem/feathers-swagger#98]
hello,
I saw this comment from the old days about how to generate swagger documentation from js docs . do you have a way or roadmap to implement this feature to this feathers plugin ?  

https://github.com/feathersjs/feathers/issues/24#issuecomment-30347346

**Comment by Mairu** [comment]
I don't see this in the scope of this package. This could be handled in another package which adds a prepared docs property to services based on js docs.
